import userRoutes from './Api/Master/user.routes.js';
import otpRoutes from './Api/Master/otp.routes.js';
import notificationsRoutes from './Api/Master/notifications.routes.js';
import notificationsMapUserRoutes from './Api/Master/notifications_map_user.routes.js';
import fileUploadRoutes from './Api/Master/file-upload.routes.js';
import membershipPackageRoutes from './Api/Master/membership-package.routes.js';
import membershipOfferHeadingsRoutes from './Api/Master/membership-offer-headings.routes.js';
import membershipOfferHeadingsLinesRoutes from './Api/Master/membership-offer-headings-lines.routes.js';
import membershipMapUserRoutes from './Api/Master/membership-map-user.routes.js';
import membershipPackageMapSubUserRoutes from './Api/Master/membership-package-map-sub-user.routes.js';
import paymentTypeRoutes from './Api/Master/payment-type.routes.js';
import paymentRoutes from './Api/Master/payment.routes.js';
import paymentUPIRoutes from './Api/Master/payment-upi.routes.js';
import taskRoutes from './Api/Master/task.routes.js';
import musicCategoryRoutes from './Api/Master/music-category.routes.js';
import templateCategoryRoutes from './Api/Master/template-category.routes.js';
import faqTypeRoutes from './Api/Master/faq-type.routes.js';
import faqRoutes from './Api/Master/faq.routes.js';
import helpCenterRoutes from './Api/Master/help-center.routes.js';
import legalPrivacyRoutes from './Api/Master/legal-privacy.routes.js';
import aboutXennarRoutes from './Api/Master/about-xennar.routes.js';
import guidedTourRoutes from './Api/Master/guided-tour.routes.js';
import reportRoutes from './Api/Master/report.routes.js';
import supportRoutes from './Api/Master/support.routes.js';

import roleRoutes from './Api/Master/role.routes.js';
import vehicleTypeRoutes from './Api/Automobile/vehicle-type.routes.js';
import vehicleTransactionTypeRoutes from './Api/Automobile/vehicle-transaction-type.routes.js';
import transmissionRoutes from './Api/Automobile/transmission.routes.js';
import fuelTypeRoutes from './Api/Automobile/fuel-type.routes.js';
import automobilesRoutes from './Api/Automobile/automobiles.routes.js';
import propertyTypeRoutes from './Api/Real_Estate/property-type.routes.js';
import propertySubTypeRoutes from './Api/Real_Estate/property-sub-type.routes.js';
import propertyTransactionTypeRoutes from './Api/Real_Estate/property-transaction-type.routes.js';
import propertyConditionRoutes from './Api/Real_Estate/property-condition.routes.js';
import propertyWashroomRoutes from './Api/Real_Estate/property-washroom.routes.js';
import propertyUserSubscribeRoutes from './Api/Real_Estate/property-user-subscribe.routes.js';
import appSubscribePackageRoutes from './Api/Real_Estate/app-subscribe-package.routes.js';
import stateRoutes from './Api/Real_Estate/state.routes.js';
import cityRoutes from './Api/Real_Estate/city.routes.js';
import imageTemplateRoutes from './Api/Real_Estate/image-template.routes.js';
import musicRoutes from './Api/Real_Estate/music.routes.js';
import propertyRoutes from './Api/Real_Estate/property.routes.js';

function routes(app) {
    app.use('/api/users', userRoutes);
    app.use('/api/otp', otpRoutes);
    app.use('/api/notifications', notificationsRoutes);
    app.use('/api/notifications-map-user', notificationsMapUserRoutes);
    app.use('/api/file-upload', fileUploadRoutes);
    app.use('/api/membership-package', membershipPackageRoutes);
    app.use('/api/membership-offer-headings', membershipOfferHeadingsRoutes);
    app.use('/api/membership-offer-headings-lines', membershipOfferHeadingsLinesRoutes);
    app.use('/api/membership-map-user', membershipMapUserRoutes);
    app.use('/api/membership-package-map-sub-user', membershipPackageMapSubUserRoutes);
    app.use('/api/payment-type', paymentTypeRoutes);
    app.use('/api/payment', paymentRoutes);
    app.use('/api/payment-upi', paymentUPIRoutes);
    app.use('/api/task', taskRoutes);
    app.use('/api/music-category', musicCategoryRoutes);
    app.use('/api/template-category', templateCategoryRoutes);
    app.use('/api/faq-type', faqTypeRoutes);
    app.use('/api/faq', faqRoutes);
    app.use('/api/help-center', helpCenterRoutes);
    app.use('/api/legal-privacy', legalPrivacyRoutes);
    app.use('/api/about-xennar', aboutXennarRoutes);
    app.use('/api/guided-tour', guidedTourRoutes);
    app.use('/api/report', reportRoutes);
    app.use('/api/support', supportRoutes);
   
    app.use('/api/roles', roleRoutes);
    app.use('/api/automobile/vehicle-type', vehicleTypeRoutes);
    app.use('/api/automobile/vehicle-transaction-type', vehicleTransactionTypeRoutes);
    app.use('/api/automobile/transmission', transmissionRoutes);
    app.use('/api/automobile/fuel-type', fuelTypeRoutes);
    app.use('/api/automobile/automobiles', automobilesRoutes);
    app.use('/api/real-estate/property-type', propertyTypeRoutes);
    app.use('/api/real-estate/property-sub-type', propertySubTypeRoutes);
    app.use('/api/real-estate/property-transaction-type', propertyTransactionTypeRoutes);
    app.use('/api/real-estate/property-condition', propertyConditionRoutes);
    app.use('/api/real-estate/property-washroom', propertyWashroomRoutes);
    app.use('/api/real-estate/property-user-subscribe', propertyUserSubscribeRoutes);
    app.use('/api/real-estate/app-subscribe-package', appSubscribePackageRoutes);
    app.use('/api/real-estate/state', stateRoutes);
    app.use('/api/real-estate/city', cityRoutes);
    app.use('/api/real-estate/image-template', imageTemplateRoutes);
    app.use('/api/real-estate/music', musicRoutes);
    app.use('/api/real-estate/property', propertyRoutes);
}

export default routes;